# Generated by Django 5.2.17 on 2026-09-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('tipo_plan', models.CharField(max_length=255, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('precio_por_usuario', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('limite_usuarios', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=255, null=True)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.plan')),
            ],
        ),
    ]
