# Generated by Django 5.2.17 on 2026-09-25 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='instancias.instanciamoodle'),
        ),
    ]
