# Generated by Django 5.2.17 on 2026-10-01 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='clientes.cliente'),
        ),
    ]
