# Generated by Django 5.2.17 on 2026-10-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_plan_cliente'),
        ('planes', '0002_suscripcion_instancia'),
    ]

    operations = [
    ]
