# Generated by Django 5.2.17 on 2026-09-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('fecha_pago', models.DateTimeField(null=True)),
                ('estado', models.CharField(max_length=255, null=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.suscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=255, null=True)),
                ('folio', models.IntegerField(null=True)),
                ('url_pdf', models.CharField(max_length=255, null=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pagos.pago')),
            ],
        ),
    ]
