# Generated by Django 5.2.17 on 2026-09-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionUsoMensual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField(null=True)),
                ('anio', models.IntegerField(null=True)),
                ('usuarios_activos', models.IntegerField(null=True)),
                ('cantidad_cursos', models.IntegerField(null=True)),
                ('cantidad_categorias', models.IntegerField(null=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instancias.instanciamoodle')),
            ],
        ),
    ]
