# Generated by Django 5.2.17 on 2026-09-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaMoodle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dominio', models.CharField(max_length=255, null=True)),
                ('version', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
        ),
    ]
