# Generated by Django 5.2.17 on 2026-10-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0002_instanciamoodle_logo_url_and_domain_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciamoodle',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instanciamoodle',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('archivada', 'Archivada')], max_length=255, null=True),
        ),
    ]
