# Generated by Django 5.2.17 on 2026-10-09 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0003_instanciamoodle_nombre_alter_instanciamoodle_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciamoodle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
